<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SI.GURS.EV="https://ipi.eprostor.sigov.si/SI.GURS.EV" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" elementFormDefault="qualified" targetNamespace="https://ipi.eprostor.sigov.si/SI.GURS.EV">
  <xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="https://ipi.eprostor.gov.si/wfs-si-gurs-ev/schemas/gml/3.2.1/gml.xsd"/>
  <xsd:complexType name="PARCELAType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="FEATUREID" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_PARCELA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="RPE_OBCINE_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="RPE_OBCINE_NAZIV" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KO_SIFKO" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PARCELA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POVRSINA" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="E" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="N" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="BONITETA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ODPRTOST" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="RK" nillable="true" type="xsd:long"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="PARCELA" substitutionGroup="gml:AbstractFeature" type="SI.GURS.EV:PARCELAType"/>
  <xsd:complexType name="PARC_ENOTAType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="1" name="FEATUREID" nillable="false" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="1" name="ID_PARC_ENOTA" nillable="false" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_PARCELA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ID_MODEL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NAZIV_MODEL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DELEZ_POVRSINE" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="RAVEN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POSPLOSENA_VREDNOST" nillable="true" type="xsd:long"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="PARC_ENOTA" substitutionGroup="gml:AbstractFeature" type="SI.GURS.EV:PARC_ENOTAType"/>
  <xsd:complexType name="STAVBAType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="FEATUREID" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_STAVBA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KO_SIFKO" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STEV_ST" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_ETAZ" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="LETO_IZG_STA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="LETO_OBN_STREHE" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="LETO_OBN_FASADE" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ID_KONSTRUKCIJA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NAZIV_KONSTRUKCIJA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="IMA_VODOVOD_DN" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="IMA_ELEKTRIKO_DN" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="IMA_KANALIZACIJO_DN" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="IMA_PLIN_DN" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ID_TIP_STAVBE" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NAZIV_TIP_STAVBE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="E" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="N" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_STANOVANJ" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_POSLOVNIH_PROSTOROV" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POV_STAVBE" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ZPS_STAVBA" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="RPE_OBCINE_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="RPE_OBCINE_NAZIV" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="STAVBA" substitutionGroup="gml:AbstractFeature" type="SI.GURS.EV:STAVBAType"/>
  <xsd:complexType name="DEL_STAVBEType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="FEATUREID" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_DEL_STAVBE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_STAVBA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STEV_DST" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STEV_STAN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POVRSINA" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPOR_POV" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_HISNE_STEVILKE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="LETO_OBN_OKEN" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="LETO_OBN_INST" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_NADSTROPJA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ID_LEGA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NAZIV_LEGA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PROSTORNINA" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="IMA_DVIGALO_DN" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINA_ETAZE" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ID_DR_DST" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NAZIV_DR_DST" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ZPS_DST" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="RPE_OBCINE_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="RPE_OBCINE_NAZIV" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="DEL_STAVBE" substitutionGroup="gml:AbstractFeature" type="SI.GURS.EV:DEL_STAVBEType"/>
  <xsd:complexType name="DEL_STAVBE_ENOTAType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="FEATUREID" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_DEL_STAVBE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ID_MODEL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="RAVEN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VPLIV" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POSPLOSENA_VREDNOST" nillable="true" type="xsd:long"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="DEL_STAVBE_ENOTA" substitutionGroup="gml:AbstractFeature" type="SI.GURS.EV:DEL_STAVBE_ENOTAType"/>
  <xsd:complexType name="PEType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="FEATUREID" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ID_PE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_DEL_STAVBE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_PARCELA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POVRSINA_PE" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VREDNOST_DODATEK" nillable="true" type="xsd:decimal"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="PE" substitutionGroup="gml:AbstractFeature" type="SI.GURS.EV:PEType"/>
</xsd:schema>
