<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SI.GURS.KN="https://ipi.eprostor.sigov.si/SI.GURS.KN" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" elementFormDefault="qualified" targetNamespace="https://ipi.eprostor.sigov.si/SI.GURS.KN">
  <xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="https://ipi.eprostor.gov.si/wfs-si-gurs-kn/schemas/gml/3.2.1/gml.xsd"/>
  <xsd:complexType name="PARCELEType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="FEATUREID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_PARCELA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="1" name="PARCELA_ID" nillable="false" type="xsd:integer"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KO_ID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NAZIV" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_PARCELE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POVRSINA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DOLOCITEV_POVRSINE" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="METODE_DOLOCITVE_POVRSINE_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="METODE_DOLOCITVE_POVRSINE_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="METODE_DOLOCITVE_POVRSINE_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="METODE_DOLOCITVE_POVRSINE_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="METODE_DOLOCITVE_POVRSINE_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="METODE_DOLOCITVE_POVRSINE_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="METODE_DOLOCITVE_POVRSINE_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="METODE_DOLOCITVE_POVRSINE_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="METODE_DOLOCITVE_POVRSINE_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNI_STATUS_ID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNI_STATUSI_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNI_STATUSI_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNI_STATUSI_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNI_STATUSI_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNI_STATUSI_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNI_STATUSI_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNI_STATUSI_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNI_STATUSI_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNI_STATUSI_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="E_CEN" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="N_CEN" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="GEOM" nillable="true" type="gml:GeometryPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DATUM_SYS" nillable="true" type="xsd:dateTime"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="BONITETA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ZNESEK_KD" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="GRAD_PARC" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="OMEJITEV" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="PARCELE" substitutionGroup="gml:AbstractFeature" type="SI.GURS.KN:PARCELEType"/>
  <xsd:complexType name="STAVBEType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="FEATUREID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_STAVBA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KO_ID" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NAZIV" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_STAVBE" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STEVILO_ETAZ" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STEVILO_STANOVANJ" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STEVILO_POSLOVNIH_PROSTOROV" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="BRUTO_TLORISNA_POVRSINA" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TIP_STAVBE_ID" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TIPI_STAVB_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TIPI_STAVB_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TIPI_STAVB_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TIPI_STAVB_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TIPI_STAVB_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TIPI_STAVB_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TIPI_STAVB_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TIPI_STAVB_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TIPI_STAVB_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ELEKTRIKA" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ELEKTRIKA_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ELEKTRIKA_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ELEKTRIKA_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ELEKTRIKA_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ELEKTRIKA_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ELEKTRIKA_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ELEKTRIKA_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ELEKTRIKA_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ELEKTRIKA_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PLIN" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PLIN_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PLIN_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PLIN_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PLIN_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PLIN_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PLIN_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PLIN_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PLIN_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PLIN_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VODOVOD" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VODOVOD_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VODOVOD_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VODOVOD_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VODOVOD_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VODOVOD_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VODOVOD_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VODOVOD_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VODOVOD_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VODOVOD_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KANALIZACIJA" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KANALIZACIJA_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KANALIZACIJA_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KANALIZACIJA_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KANALIZACIJA_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KANALIZACIJA_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KANALIZACIJA_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KANALIZACIJA_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KANALIZACIJA_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KANALIZACIJA_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="LETO_IZGRADNJE" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="LETO_OBNOVE_FASADE" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="LETO_OBNOVE_STREHE" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINA_H1" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINA_H2" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINA_H3" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POLOZAJNA_NATANCNOST_STAVBE_ID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POLOZAJNE_NATANCNOSTI_STAVBE_SIFRA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POLOZAJNE_NATANCNOSTI_STAVBE_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POLOZAJNE_NATANCNOSTI_STAVBE_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POLOZAJNE_NATANCNOSTI_STAVBE_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POLOZAJNE_NATANCNOSTI_STAVBE_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POLOZAJNE_NATANCNOSTI_STAVBE_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POLOZAJNE_NATANCNOSTI_STAVBE_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POLOZAJNE_NATANCNOSTI_STAVBE_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POLOZAJNE_NATANCNOSTI_STAVBE_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKA_NATANCNOST_STAVBE_ID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKE_NATANCNOSTI_STAVBE_SIFRA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKE_NATANCNOSTI_STAVBE_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKE_NATANCNOSTI_STAVBE_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKE_NATANCNOSTI_STAVBE_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKE_NATANCNOSTI_STAVBE_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKE_NATANCNOSTI_STAVBE_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKE_NATANCNOSTI_STAVBE_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKE_NATANCNOSTI_STAVBE_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKE_NATANCNOSTI_STAVBE_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NOSILNA_KONSTRUKCIJA_ID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NOSILNE_KONSTRUKCIJE_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NOSILNE_KONSTRUKCIJE_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NOSILNE_KONSTRUKCIJE_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NOSILNE_KONSTRUKCIJE_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NOSILNE_KONSTRUKCIJE_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NOSILNE_KONSTRUKCIJE_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NOSILNE_KONSTRUKCIJE_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NOSILNE_KONSTRUKCIJE_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NOSILNE_KONSTRUKCIJE_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="CENTROID_GEOM" nillable="true" type="gml:GeometryPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TLORIS_GEOM" nillable="true" type="gml:GeometryPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NADZEMNI_GEOM" nillable="true" type="gml:GeometryPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PODZEMNI_GEOM" nillable="true" type="gml:GeometryPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="TEREN_GEOM" nillable="true" type="gml:GeometryPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="OBRIS_GEOM" nillable="true" type="gml:GeometryPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DATUM_SYS" nillable="true" type="xsd:dateTime"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKI_DATUM_STAVBE_ID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKI_DATUMI_STAVBE_SIFRA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKI_DATUMI_STAVBE_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKI_DATUMI_STAVBE_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKI_DATUMI_STAVBE_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKI_DATUMI_STAVBE_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKI_DATUMI_STAVBE_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKI_DATUMI_STAVBE_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKI_DATUMI_STAVBE_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VISINSKI_DATUMI_STAVBE_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUS_VPISA_ID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_STAVBE_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_STAVBE_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_STAVBE_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_STAVBE_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_STAVBE_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_STAVBE_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_STAVBE_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_STAVBE_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_STAVBE_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="E_CEN" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="N_CEN" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STEVILKA_PRITL_ETAZE" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="RPE_OBCINE_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="RPE_OBCINE_NAZIV" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="STAVBE" substitutionGroup="gml:AbstractFeature" type="SI.GURS.KN:STAVBEType"/>
  <xsd:complexType name="STAVBE_OBRISType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="FEATUREID" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_STAVBA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KO_ID" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_STAVBE" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="OBRIS_GEOM" nillable="true" type="gml:GeometryPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DATUM_SYS" nillable="true" type="xsd:dateTime"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="E_CEN" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="N_CEN" nillable="true" type="xsd:decimal"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="STAVBE_OBRIS" substitutionGroup="gml:AbstractFeature" type="SI.GURS.KN:STAVBE_OBRISType"/>
  <xsd:complexType name="DELI_STAVBType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="FEATUREID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_DEL_STAVBE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="1" name="DEL_STAVBE_ID" nillable="false" type="xsd:integer"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_STAVBA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_HISNA_STEVILKA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNIK_ID" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NAZIV" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NASLOV" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTA_DEJANSKE_RABE_DEL_ST_ID" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_DEJANSKIH_RAB_DEL_ST_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_DEJANSKIH_RAB_DEL_ST_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_DEJANSKIH_RAB_DEL_ST_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_DEJANSKIH_RAB_DEL_ST_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_DEJANSKIH_RAB_DEL_ST_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_DEJANSKIH_RAB_DEL_ST_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_DEJANSKIH_RAB_DEL_ST_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_DEJANSKIH_RAB_DEL_ST_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_DEJANSKIH_RAB_DEL_ST_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DVIGALO" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DVIGALO_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DVIGALO_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DVIGALO_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DVIGALO_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DVIGALO_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DVIGALO_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DVIGALO_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DVIGALO_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DVIGALO_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="LETO_OBNOVE_INSTALACIJ" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="LETO_OBNOVE_OKEN" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="POVRSINA" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUS" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_DELA_STAVBE_SIFRA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_DELA_STAVBE_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_DELA_STAVBE_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_DELA_STAVBE_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_DELA_STAVBE_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_DELA_STAVBE_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_DELA_STAVBE_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_DELA_STAVBE_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_VPISA_DELA_STAVBE_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KO_ID" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_STAVBE" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_DELA_STAVBE" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPORABNA_POVRSINA" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DATUM_SYS" nillable="true" type="xsd:dateTime"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="PROSTORNINA_CISTERN_SILOSOV" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NACIN_DOLOCITVE_POVRSINE_DELA_STAVBE_ID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NACINI_DOLOCITVE_POVRSIN_DELA_STAVBE_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NACINI_DOLOCITVE_POVRSIN_DELA_STAVBE_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NACINI_DOLOCITVE_POVRSIN_DELA_STAVBE_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NACINI_DOLOCITVE_POVRSIN_DELA_STAVBE_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NACINI_DOLOCITVE_POVRSIN_DELA_STAVBE_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NACINI_DOLOCITVE_POVRSIN_DELA_STAVBE_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NACINI_DOLOCITVE_POVRSIN_DELA_STAVBE_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NACINI_DOLOCITVE_POVRSIN_DELA_STAVBE_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NACINI_DOLOCITVE_POVRSIN_DELA_STAVBE_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="UPRAVNIK_STATUS" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_UPRAVNIKOV_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_UPRAVNIKOV_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_UPRAVNIKOV_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_UPRAVNIKOV_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_UPRAVNIKOV_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_UPRAVNIKOV_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_UPRAVNIKOV_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_UPRAVNIKOV_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="STATUSI_UPRAVNIKOV_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_STANOVANJE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_STANOVANJA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTA_ID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_STANOVANJ_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_STANOVANJ_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_STANOVANJ_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_STANOVANJ_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_STANOVANJ_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_STANOVANJ_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_STANOVANJ_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_STANOVANJ_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="VRSTE_STANOVANJ_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_ETAZE_GLAVNEGA_VHODA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ETAZE_DELA_STAVBE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NASLOV_DELA_STAVBE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ETAZNA_LASTNINA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ETAZNA_LASTNINA_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ETAZNA_LASTNINA_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ETAZNA_LASTNINA_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ETAZNA_LASTNINA_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ETAZNA_LASTNINA_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ETAZNA_LASTNINA_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ETAZNA_LASTNINA_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ETAZNA_LASTNINA_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ETAZNA_LASTNINA_OPIS_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_SIFRA" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_NAZIV_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_OPIS_SL" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_NAZIV_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_OPIS_EN" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_NAZIV_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_OPIS_IT" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_NAZIV_HU" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="SKUPNI_DEL_ETAZNA_LASTNINA_OPIS_HU" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="DELI_STAVB" substitutionGroup="gml:AbstractFeature" type="SI.GURS.KN:DELI_STAVBType"/>
  <xsd:complexType name="NASLOVI_STAVBEType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="FEATUREID" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_STAVBA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="KO_ID" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ST_STAVBE" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="EID_HISNA_STEVILKA" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="NASLOV_STAVBE" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="DATUM_SYS" nillable="true" type="xsd:dateTime"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="NASLOVI_STAVBE" substitutionGroup="gml:AbstractFeature" type="SI.GURS.KN:NASLOVI_STAVBEType"/>
</xsd:schema>
